apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: basic-go-as-other-xqnl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: basic-go-as-other-xqnl
    app.kubernetes.io/part-of: bg
  name: basic-go-as-other-xqnl
  namespace: pmacik-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: basic-go-as-other-xqnl
status:
  loadBalancer: {}
